Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,18 +11,17 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest]
+        os: [ubuntu-latest, windows-latest, macos-latest]
         qt: [5.15.2]
 
 # =================================
     runs-on: ${{ matrix.os }}
 
-    container:
-      image: ubuntu:20.04
-      options: --privileged
+    container: ${{ matrix.os == 'ubuntu-latest' && 'ubuntu:20.04' || '' }}
 
     steps:
-    - name: Install dependencies
+    - name: Install Linux dependencies
+      if: runner.os == 'Linux'
       run: |
         export DEBIAN_FRONTEND=noninteractive
         apt-get update
@@ -62,6 +61,7 @@ jobs:
           python3-pip \
           python3-setuptools \
           python3-wheel \
+          ninja-build \
           sudo \
           wget
 
@@ -74,10 +74,30 @@ jobs:
       run: echo "VERSION=$(echo $GITHUB_REF | sed 's|refs/tags/||')" >> $GITHUB_ENV
       shell: bash
 
+    - name: Install Sentry CLI
+      run: |
+        if [ "$RUNNER_OS" == "Windows" ]; then
+          LATEST_VERSION=$(curl -s https://api.github.com/repos/getsentry/sentry-cli/releases/latest | jq -r .tag_name)
+          curl -LO "https://github.com/getsentry/sentry-cli/releases/download/$LATEST_VERSION/sentry-cli-Windows-x86_64.exe"
+          mv sentry-cli-Windows-x86_64.exe sentry-cli.exe
+          
+          ACTUAL_VERSION=$(./sentry-cli.exe -V 2>&1 | tr -d '\r')
+
+          if [[ ! "$ACTUAL_VERSION" =~ ^sentry-cli ]]; then
+            echo "Downloaded Sentry CLI binary is invalid!" >&2
+            exit 1
+          fi
+        else
+          curl -sL https://sentry.io/get-cli/ | bash
+        fi
+      shell: bash
+
     - name: Install Qt
       uses: jurplel/install-qt-action@v4
       with:
         version: ${{ matrix.qt }}
+        arch: ${{ matrix.os == 'windows-latest' && matrix.qt == '5.15.2' && 'win32_msvc2019' || '' }}
+        cache: true
         aqtversion: ==3.1.*
         modules: ${{ startsWith(matrix.qt, '6') && 'qtmultimedia qtimageformats debug_info' || 'debug_info' }}
         setup-python: 'false'
@@ -87,7 +107,20 @@ jobs:
       with:
         key: ${{ matrix.qt }}
 
+# =================================
+
+    - name: Compile Sentry SDK Linux
+      if: runner.os == 'Linux'
+      run: |
+        git clone --recursive https://github.com/getsentry/sentry-native.git
+        mkdir -p sentry-native/build
+        cd sentry-native/build
+        cmake .. -B build -D SENTRY_BACKEND=crashpad -D CMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
+        cmake --build build --parallel
+        cmake --install build --prefix ../../thirdparty/sentry
+
     - name: Build Ubuntu
+      if: runner.os == 'Linux'
       run: |
         mkdir build
         cd build
@@ -95,11 +128,12 @@ jobs:
         make -j4
 
     - name: Test Ubuntu
+      if: runner.os == 'Linux'
       run: |
-        cd build/test
-        ./WPanda-test -platform offscreen
+        ./build/test/WPanda-test -platform offscreen
 
     - name: linuxdeployqt
+      if: runner.os == 'Linux'
       run: |
         mkdir -p appimage
         cp app/resources/wpanda.desktop appimage/wpanda.desktop
@@ -111,8 +145,151 @@ jobs:
         rm ./linuxdeployqt-continuous-x86_64.AppImage
         mv wiRedPanda-$VERSION-x86_64.AppImage wiRedPanda-$VERSION-Ubuntu-Qt${{ matrix.qt }}.AppImage
 
+    - name: Upload Debug Symbols to Sentry
+      if: runner.os == 'Linux'
+      env:
+        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+      run: |
+        sentry-cli login --auth-token "$SENTRY_AUTH_TOKEN"
+        sentry-cli releases new "wiredpanda@$VERSION" -p wiredpanda
+        sentry-cli debug-files upload --include-sources -p wiredpanda build/app/
+        sentry-cli debug-files upload --include-sources -p wiredpanda $QT_ROOT_DIR
+        sentry-cli releases set-commits --auto "wiredpanda@$VERSION" --log-level=debug
+
     - name: Publish Ubuntu
       uses: softprops/action-gh-release@v2
+      if: runner.os == 'Linux'
       with:
         fail_on_unmatched_files: true
         files: '*.AppImage'
+
+# =================================
+
+    - name: Setup MSVC Toolchain
+      if: runner.os == 'Windows'
+      uses: pbeast/gha-setup-vsdevenv@master
+      with:
+        arch: ${{ startsWith(matrix.qt, '5') && 'x86' || 'x64' }}
+
+    - name: Compile Sentry SDK Windows
+      if: runner.os == 'Windows'
+      run: |
+        git clone --recursive https://github.com/getsentry/sentry-native.git
+        mkdir -p sentry-native/build
+        cd sentry-native/build
+        cmake .. -B build -G "Visual Studio 17 2022" ${{ matrix.qt == '5.15.2' && '-A Win32' || '' }}
+        cmake --build build --config RelWithDebInfo
+        cmake --install build --prefix ../../thirdparty/sentry --config RelWithDebInfo
+
+    - name: Build Windows
+      if: runner.os == 'Windows'
+      run: |
+        choco install jom
+        mkdir build
+        cd build
+        qmake ../WPanda.pro
+        jom
+        cp ../thirdparty/sentry/bin/crashpad_handler.exe app/release/
+        cp ../thirdparty/sentry/bin/sentry.dll app/release/
+        cp ../thirdparty/sentry/bin/crashpad_wer.dll app/release/
+        cp ../thirdparty/sentry/bin/sentry.dll test/release/
+
+    - name: Test Windows
+      if: runner.os == 'Windows'
+      run: |
+        cd build
+        jom check
+
+    - name: windeployqt
+      if: runner.os == 'Windows'
+      run : |
+        cp -r examples build/app/release
+        cd build/app/release
+        windeployqt --compiler-runtime wiredpanda.exe
+        rm wiredpanda_pch.obj
+        rm wiredpanda_pch.pch
+        cd ..
+        ren release wiredpanda-$env:VERSION
+        Compress-Archive -Path wiredpanda-$env:VERSION -DestinationPath wiRedPanda-$env:VERSION-Windows-Qt${{ matrix.qt }}-Portable.zip
+
+    - name: Upload Debug Symbols to Sentry
+      if: runner.os == 'Windows'
+      env:
+        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+      run: |
+        ./sentry-cli.exe login --auth-token $env:SENTRY_AUTH_TOKEN
+        ./sentry-cli.exe releases new wiredpanda@$env:VERSION -p wiredpanda
+        ./sentry-cli.exe debug-files upload --include-sources -p wiredpanda build/app/
+        ./sentry-cli.exe debug-files upload --include-sources -p wiredpanda D:/a/wiRedPanda/Qt/
+        ./sentry-cli.exe releases set-commits --auto wiredpanda@$env:VERSION --log-level=debug
+
+    - name: Publish Windows
+      if: runner.os == 'Windows'
+      uses: softprops/action-gh-release@v2
+      with:
+        fail_on_unmatched_files: true
+        files: 'build/app/*.zip'
+
+# =================================
+
+    - name: Compile Sentry SDK macOS
+      if: runner.os == 'macOS'
+      run: |
+        git clone --recursive https://github.com/getsentry/sentry-native.git
+        mkdir -p sentry-native/build
+        cd sentry-native/build
+        cmake .. -B build -D SENTRY_BACKEND=crashpad -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_OSX_ARCHITECTURES="x86_64;arm64"
+        cmake --build build --parallel
+        cmake --install build --prefix ../../thirdparty/sentry
+
+    - name: Build macOS
+      if: runner.os == 'macOS'
+      run: |
+        mkdir build
+        cd build
+        qmake ../WPanda.pro
+        make -j3
+        mkdir -p app/wiredpanda.app/Contents/MacOS
+        mkdir -p app/wiredpanda.app/Contents/Frameworks
+        cp ../thirdparty/sentry/bin/crashpad_handler app/wiredpanda.app/Contents/MacOS/
+        cp ../thirdparty/sentry/lib/libsentry.dylib app/wiredpanda.app/Contents/Frameworks/
+        mkdir -p test/WPanda-test.app/Contents/MacOS
+        mkdir -p test/WPanda-test.app/Contents/Frameworks
+        cp ../thirdparty/sentry/lib/libsentry.dylib test/WPanda-test.app/Contents/Frameworks/
+
+    - name: Generate dSYM Symbols
+      if: runner.os == 'macOS'
+      run: |
+        cd build/app
+        dsymutil wiredpanda.app/Contents/MacOS/wiredpanda -o wiredpanda.app.dSYM
+
+    - name: Test macOS
+      if: runner.os == 'macOS'
+      run: |
+        cd build
+        make check
+
+    - name: macdeployqt
+      if: runner.os == 'macOS'
+      run: |
+        cd build/app
+        macdeployqt wiredpanda.app -dmg
+        mv wiredpanda.dmg wiRedPanda-$VERSION-macOS-Qt${{ matrix.qt }}.dmg
+
+    - name: Upload Debug Symbols to Sentry
+      if: runner.os == 'macOS'
+      env:
+        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+      run: |
+        sentry-cli login --auth-token "$SENTRY_AUTH_TOKEN"
+        sentry-cli releases new "wiredpanda@$VERSION" -p wiredpanda
+        sentry-cli debug-files upload --include-sources -p wiredpanda build/app/
+        sentry-cli debug-files upload --include-sources -p wiredpanda $QT_ROOT_DIR
+        sentry-cli releases set-commits --auto "wiredpanda@$VERSION" --log-level=debug
+
+    - name: Publish macOS
+      if: runner.os == 'macOS'
+      uses: softprops/action-gh-release@v2
+      with:
+        fail_on_unmatched_files: true
+        files: 'build/app/*.dmg'
